sudo: required
env:
  global:
  - REPO=bncprojects/ecs-instance-drainer
  - secure: lSROAbdS6vuKMbJ1pdVKwRY07E2jJOL5XpnNVLtJaVUjfshqJwF9kRgqg8VVEgKZl/h8fPedPjh9X16TEJNLc7Vc1PZuLufe15HAIzzeTOPc7kQrpsSMnPwnaWxNyT1ZGjF+cbHhuFyB3J9BpsDv+0sVM/5uuO+gmxOiegRp1oX5/wa76FJIWpBCTG+YgiR8LqP7Bo9ccQQ2ItzqhqTRD5wzGzE2bEiBeJnqGKFrD9ZXld9BrxYL3TmhtP4az9TKXQqBTgYFtoreObJkjIg2utJlufKpVRBlC0QpxfxNVRXYZMx+uEMHXU6n6PZFCc+sdxhr7DMsj5/U6pHTgIeMZ1VYiG4CwPUEE3h869PSsdQwzCSGDKppykjTnZPMg2Oq0a7YuZCSZj5UIHwwyvMpHxnF2VhVEHemtgjziFAjwbWroczVFm9P1sdWiSaSu5lJ0kb1sHjrfWwbHRQ1m3LrWhSTbMkQmmkjUgQHo9uYd236Tv0l61ZWhom0vTuLhwreruzwbcC5UmhGuDdoVNh5KkvN7B2ItFSqsLytkAVBIhmtvDwiB4m1mY5uBck9QJhMHjSfruJYi6BvEW3l1pNaqgwJk1GPs4jt6Ic0nwT8srrb6jUnzFErjzhXfrNa55ExqtyXfyymOxb9EU+UhgvGuhf1fBZlR+V6EnVPSw4wqVE=
  - secure: D/dWL21F/88faIRfJg5LbMBclQY86ho9ByeXnV+F586ctv4HGa2b95tjBfIyUkylIbigSaAsk4Ue+GYONxl7L80Wr5v9BNRk/WB4vo6Yd7eAYcHXZz24Ty2ziRBr2u4OswIF6Ul3q0YbjmbOMJrqVVR8Qhs1/qlXI8LouYEix4Fsbrpy2ZcdNWFmwHnBgx81G4YUf4PkFlFOYwum0RIODrhZRgYmrta6vdJMHDWz4Dtet3sQhNq8ms2eh7aTDgLo5i7Scqzm3gG9XBzfr/StIXdkpwbsoP9woe/gFVQThcyCi/Gz+HhL+e8ownN5XZA4cQwQHi7cyrDBkIP+WL6Eh5rYRxGmixKi+PAd4NjWEdbSLNFb71abWLKKB0ESH1apkqHHZEgUH7jZPWVq5Y590un9udv98kbBeDk4USyf+Lb+IQx0SoZNkF01xCmJhck++2G6wXMRIXegxGivLxskdK2MX2TgmDcSN/bqYrAK0wiDbNH4y7zy4YfZH3LYG1E+HMmZ4VXMvRMQc89kg/74SeydIfLnR56sd8L7xQYIW+eg+T0mO1iaSSdT+nznP8nchku1xb4kAvQWPXBRQd6nsl9isBkJwGFy4AxLyB1yV8mTc3PqgCruMxnUMjCMQT//VtvW2e9zlhx4pwM0r5s9+XsbyZCBOdy7uFSJazvesbA=
language: go
go:
- 1.12.x
services:
- docker
branches:
  only:
  - master
before_script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH | sed "s/\//-/g"; fi`
script:
- go test ./... -coverprofile=coverage.txt -covermode=atomic -v
- CGO_ENABLED=0 GOOS=linux go build -a -o ecs-instance-drainer .
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- bash <(curl -s https://codecov.io/bash)  || echo "Codecov did not collect coverage
  reports"
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
